# permissions for end users to view pvccons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pvccon-viewer-role
rules:
- apiGroups:
  - batch.example.com
  resources:
  - pvccons
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.example.com
  resources:
  - pvccons/status
  verbs:
  - get
